baseURL = "https://karolpiekar.ski/exploring-city-parks-with-instagram"
languageCode = "en-gb"
title = "Exploring the city parks with Instagram"

[params]
  [params.homepage]
    show_call_box = false
    hide_view_all_services = true  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "Exploring the city parks with Instagram"

  [params.homepage_meta_tags]
    meta_description = "An experimental research initiative investigating Bratislava parks through Instagram data."
    meta_og_title = "Exploring the city parks with Instagram"
    meta_og_type = "website"
    meta_og_url = "https://karolpiekar.ski/exploring-city-parks-with-instagram"
    meta_og_image = "https://karolpiekar.ski/exploring-city-parks-with-instagram/images/insta/instagram/1650159203099515076.jpg"
    meta_og_description = "An experimental research initiative investigating Bratislava parks through Instagram data."

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Based on Hugo-Serif theme by <a class="zerostatic" href="https://www.zerostatic.io">zerostatic.io</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Parks"
    url = "/#parks"
    weight = 1

  [[menu.main]]
      name = "Process"
      url = "/#how-to"
      weight = 2

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

  # Footer Menu

  [[menu.footer]]
    name = "Parks"
    url = "/#parks"
    weight = 1

  [[menu.footer]]
      name = "Process"
      url = "/#how-to"
      weight = 2

  [[menu.footer]]
      name = "About"
      url = "/about/"
      weight = 3
